
openapi: "3.0.0"
info:
  title: Expense Tracker API
  version: 1.0.0
  description: Full API documentation for Expense Tracker backend.
servers:
  - url: http://localhost:3000/api/v1
    description: Local server

components:
  securitySchemes: 
    bearerAuth: 
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
      
security: 
  - bearerAuth: []
      
    
tags:
  - name: Auth
    description: Authentication and authorization endpoints
  - name: Users
    description: User management endpoints
  - name: Expenses
    description: Expenses Management endpoints
  - name: Categories
    description: Category management endpoints
